/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * test openapi - version 1.0.0
 *
 * 测试交互文档
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
	"login.get_login_current_user": ["GET", "/login/current-user"],
	"login.get_login_get_menus": ["GET", "/login/get-menus"],
	"login.post_login_auth_login": ["POST", "/login/auth-login"],
	"workbench.get_workbench_query_current_user_info": ["GET", "/c4/workbench/query-current-user-info"],
	"workbench.post_workbench_enrollment_save": ["POST", "/c4/workbench/enrollment/save"],
	"workbench.get_workbench_enrollment_record": ["GET", "/c4/workbench/enrollment/record"],
	"workbench.get_workbench_enrollment_detail": ["GET", "/c4/workbench/enrollment/detail"],
	"customer.get_customer": ["GET", "/c4/customer"],
	"customer.get_customer_detail": ["GET", "/c4/customer/detail"],
	"customer.get_customer_lesson": ["GET", "/c4/customer/lesson"],
	"class.get_class_query_myclass": ["GET", "/c4/class/query-myclass"],
	"class.get_class_query_class_student_list": ["GET", "/c4/class/queryClassStudentList"],
	"class.get_class_query_class_student_detail": ["GET", "/c4/class/queryClassStudentDetail"],
	"class.get_class_query_class_student_course_list": ["GET", "/c4/class/queryClassStudentCourseList"],
	"homework.get_homework_list": ["GET", "/c4/homework/list"],
	"homework.get_homework_detail": ["GET", "/c4/homework/detail"],
	"homework.post_homework_add": ["POST", "/c4/homework/add"],
	"homework.post_homework_comment": ["POST", "/c4/homework/comment"],
	"comment.get_comment_record": ["GET", "/c4/getcommentrecord"],
	"rollcall.get_rollcall_record": ["GET", "/c4/getrollcallrecord"],
	"student.post_add_intended_student": ["POST", "/c4/addintendedstudent"],
	"teacher.get_teacher_list": ["GET", "/c4/teacher/list"],
	"teacher.get_class_list": ["GET", "/c4/class/list"],
	"scheduling.post_scheduling_repeat_create": ["POST", "/c4/scheduling/repeat/create"],
	"scheduling.post_scheduling_free_create": ["POST", "/c4/scheduling/free/create"],
	"course.get_course_get_common_datetime": ["GET", "/course/get-common-datetime"],
	"course.get_course_record_comment_cs_comment_list": ["GET", "/course/record-comment/cs-comment-list"],
	"course.put_course_record_comment_comment_stu": ["PUT", "/course/record-comment/comment-stu"],
	"course.get_course_record_name_get_detail_cs": ["GET", "/course/record-name/get-detail-cs"],
	"course.get_course_record_name_get_cs_stu_list": ["GET", "/course/record-name/get-cs-stu-list"],
	"course.put_course_record_name_set_status": ["PUT", "/course/record-name/set-status"],
	"course.get_course_record_name_stu_list": ["GET", "/course/record-name/stu-list"],
	"course.get_course_record_name_stu_course_list": ["GET", "/course/record-name/stu-course-list"],
	"course.post_course_record_name_stu_add_to_cs": ["POST", "/course/record-name/stu-add-to-cs"],
	"article.get_article": ["GET", "/article"],
	"article.post_article": ["POST", "/article"],
	"article.put_article": ["PUT", "/article"],
	"article.delete_article_id": ["DELETE", "/article/{id}"],
};
