/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * test openapi - version 1.0.0
 *
 * 测试交互文档
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
	"login.get_login_current_user": ["GET", "/login/current-user"],
	"login.get_login_get_menus": ["GET", "/login/get-menus"],
	"login.post_login_auth_login": ["POST", "/login/auth-login"],
	"schedule.post_schedule_appointment": ["POST", "/schedule/appointment"],
	"schedule.get_schedule_query": ["GET", "/schedule/query"],
	"schedule.post_schedule_leave": ["POST", "/schedule/leave"],
	"schedule.post_schedule_sign_in": ["POST", "/schedule/sign-in"],
	"sCenter.get_app_sCenter_advertisement": ["GET", "/app/sCenter/advertisement"],
	"sCenter.get_app_sCenter_advertisementList": ["GET", "/app/sCenter/advertisementList"],
	"sCenter.get_app_sCenter_student_redpoint": ["GET", "/app/sCenter/student/redpoint"],
	"home.get_home_attendance_records_page_query_by_student_id": ["GET", "/home/attendance_records/page/query-by-student_id"],
	"home.post_home_attendance_records_evaluate": ["POST", "/home/attendance_records/evaluate"],
	"home.get_home_class_info_query_by_class_id": ["GET", "/home/class/info/query-by-class_id"],
	"home.get_home_class_page_query_by_student_id": ["GET", "/home/class/page/query-by-student_id"],
	"home.get_home_class_student_list_query_by_class_id": ["GET", "/home/class/student/list/query-by-class_id"],
	"home.get_c1_home_card_list": ["GET", "/c1/home/card-list"],
	"home.get_c1_home_card_rule": ["GET", "/c1/home/card-rule"],
	"home.put_c1_card_put": ["PUT", "/c1/card/put"],
	"home.get_c1_exchange_query_allGoods": ["GET", "/c1/exchange/query-allGoods"],
	"home.get_c1_exchange_goods_detail_id": ["GET", "/c1/exchange/goods-detail/{id}"],
	"home.get_c1_exchange_query_acceptGoods": ["GET", "/c1/exchange/query-acceptGoods"],
	"home.get_c1_exchange_query_rule": ["GET", "/c1/exchange/query-rule"],
	"home.post_c1_exchange_submit": ["POST", "/c1/exchange/submit"],
	"home.get_c1_registration_records_query_records": ["GET", "/c1/registration-records/query-records"],
	"home.get_c1_review_records_query_reviews": ["GET", "/c1/review-records/query-reviews"],
	"home.get_c1_home_score_query_score_list": ["GET", "/c1/home/score/query-score-list"],
	"home.get_c1_homework": ["GET", "/c1/homework"],
	"home.get_c1_homework_detail": ["GET", "/c1/homework/detail"],
	"home.post_c1_homework_submit": ["POST", "/c1/homework/submit"],
	"home.delete_c1_homework_delete": ["DELETE", "/c1/homework/delete"],
	"article.get_article": ["GET", "/article"],
	"article.post_article": ["POST", "/article"],
	"article.put_article": ["PUT", "/article"],
	"article.delete_article_id": ["DELETE", "/article/{id}"],
};
