/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * test openapi - version 1.0.0
 *
 * 测试交互文档
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'login.get_login_current_user': ['GET', '/login/current-user'],
  'login.get_login_get_menus': ['GET', '/login/get-menus'],
  'login.post_login_auth_login': ['POST', '/login/auth-login'],
  'article.get_article': ['GET', '/article'],
  'article.post_article': ['POST', '/article'],
  'article.put_article': ['PUT', '/article'],
  'article.delete_article_id': ['DELETE', '/article/{id}']
};
