/* tslint:disable */
/* eslint-disable */
/**
 * test openapi - version 1.0.0
 *
 * 测试交互文档
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from "alova";
import type { $$userConfigMap, alovaInstance } from ".";
import type apiDefinitions from "./apiDefinitions";

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
	CollapsedAlova extends Alova<
		AlovaGenerics<
			any,
			any,
			infer RequestConfig,
			infer Response,
			infer ResponseHeader,
			infer L1Cache,
			infer L2Cache,
			infer SE
		>
	>
		? Omit<
				AlovaMethodCreateConfig<
					AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
					any,
					Responded
				>,
				"params"
			>
		: never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
	DefinitionKey extends keyof typeof apiDefinitions,
	Default,
> = DefinitionKey extends keyof UserMethodConfigMap
	? UserMethodConfigMap[DefinitionKey]["transform"] extends (...args: any[]) => any
		? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]["transform"]>>
		: Default
	: Default;
type Alova2Method<
	Responded,
	DefinitionKey extends keyof typeof apiDefinitions,
	CurrentConfig extends Alova2MethodConfig<any>,
> =
	CollapsedAlova extends Alova<
		AlovaGenerics<
			any,
			any,
			infer RequestConfig,
			infer Response,
			infer ResponseHeader,
			infer L1Cache,
			infer L2Cache,
			infer SE
		>
	>
		? Method<
				AlovaGenerics<
					CurrentConfig extends undefined
						? ExtractUserDefinedTransformed<DefinitionKey, Responded>
						: CurrentConfig["transform"] extends (...args: any[]) => any
							? Awaited<ReturnType<CurrentConfig["transform"]>>
							: ExtractUserDefinedTransformed<DefinitionKey, Responded>,
					any,
					RequestConfig,
					Response,
					ResponseHeader,
					L1Cache,
					L2Cache,
					SE
				>
			>
		: never;

export interface Menu_item {
	/**
	 * 唯一编号
	 * ---
	 */
	id: string;
	/**
	 * 菜单名称
	 * ---
	 */
	text: string;
	/**
	 * 菜单图标
	 * ---
	 */
	icon: string;
	/**
	 * 父编号
	 * ---
	 */
	pid?: string;
	/**
	 * 子菜单
	 * ---
	 */
	children?: Array<{
		/**
		 * 唯一编号
		 * ---
		 */
		id: string;
		/**
		 * 菜单名称
		 * ---
		 */
		text: string;
		/**
		 * 菜单图标
		 * ---
		 */
		icon: string;
		/**
		 * 父编号
		 * ---
		 */
		pid?: string;
		/**
		 * 子菜单
		 * ---
		 */
		children?: object[];
	}>;
}
declare global {
	interface Apis {
		login: {
			/**
			 * ---
			 *
			 * [GET] 获取当前用户
			 *
			 * **path:** /login/current-user
			 *
			 * ---
			 *
			 * **Response**
			 * ```ts
			 * type Response = {
			 *   // [title] 状态码
			 *   code: number
			 *   // [title] 提示信息
			 *   message: string
			 *   // [title] 数据
			 *   data?: {
			 *     // [title] 唯一标识
			 *     id: string
			 *     // [title] 用户名
			 *     username: string
			 *     // [title] 头像地址
			 *     avatar: string
			 *     // [title] 是否启用
			 *     isEnabled: number
			 *     // [title] 角色列表
			 *     // [items] start
			 *     // [items] end
			 *     roles: string[]
			 *   }
			 * }
			 * ```
			 */
			get_login_current_user<
				Config extends Alova2MethodConfig<{
					/**
					 * 状态码
					 * ---
					 */
					code: number;
					/**
					 * 提示信息
					 * ---
					 */
					message: string;
					/**
					 * 数据
					 * ---
					 */
					data?: {
						/**
						 * 唯一标识
						 * ---
						 */
						id: string;
						/**
						 * 用户名
						 * ---
						 */
						username: string;
						/**
						 * 头像地址
						 * ---
						 */
						avatar: string;
						/**
						 * 是否启用
						 * ---
						 */
						isEnabled: number;
						/**
						 * 角色列表
						 * ---
						 */
						roles: string[];
					};
				}>,
			>(
				config?: Config,
			): Alova2Method<
				{
					/**
					 * 状态码
					 * ---
					 */
					code: number;
					/**
					 * 提示信息
					 * ---
					 */
					message: string;
					/**
					 * 数据
					 * ---
					 */
					data?: {
						/**
						 * 唯一标识
						 * ---
						 */
						id: string;
						/**
						 * 用户名
						 * ---
						 */
						username: string;
						/**
						 * 头像地址
						 * ---
						 */
						avatar: string;
						/**
						 * 是否启用
						 * ---
						 */
						isEnabled: number;
						/**
						 * 角色列表
						 * ---
						 */
						roles: string[];
					};
				},
				"login.get_login_current_user",
				Config
			>;
			/**
			 * ---
			 *
			 * [GET] 获取当前用户的菜单
			 *
			 * **path:** /login/get-menus
			 *
			 * ---
			 *
			 * **Response**
			 * ```ts
			 * type Response = {
			 *   // [title] 状态码
			 *   code: number
			 *   // [title] 提示信息
			 *   message: string
			 *   // [title] 数据
			 *   // [items] start
			 *   // [items] end
			 *   data?: Array<{
			 *     // [title] 唯一编号
			 *     id: string
			 *     // [title] 菜单名称
			 *     text: string
			 *     // [title] 菜单图标
			 *     icon: string
			 *     // [title] 父编号
			 *     pid?: string
			 *     // [title] 子菜单
			 *     // [items] start
			 *     // [items] end
			 *     children?: Array<{
			 *       // [title] 唯一编号
			 *       id: string
			 *       // [title] 菜单名称
			 *       text: string
			 *       // [title] 菜单图标
			 *       icon: string
			 *       // [title] 父编号
			 *       pid?: string
			 *       // [title] 子菜单
			 *       // [items] start
			 *       // [items] end
			 *       children?: object[]
			 *     }>
			 *   }>
			 * }
			 * ```
			 */
			get_login_get_menus<
				Config extends Alova2MethodConfig<{
					/**
					 * 状态码
					 * ---
					 */
					code: number;
					/**
					 * 提示信息
					 * ---
					 */
					message: string;
					/**
					 * 数据
					 * ---
					 */
					data?: Menu_item[];
				}>,
			>(
				config?: Config,
			): Alova2Method<
				{
					/**
					 * 状态码
					 * ---
					 */
					code: number;
					/**
					 * 提示信息
					 * ---
					 */
					message: string;
					/**
					 * 数据
					 * ---
					 */
					data?: Menu_item[];
				},
				"login.get_login_get_menus",
				Config
			>;
			/**
			 * ---
			 *
			 * [POST] 登录接口
			 *
			 * **path:** /login/auth-login
			 *
			 * ---
			 *
			 * **RequestBody**
			 * ```ts
			 * type RequestBody = {
			 *   username: string
			 *   password: string
			 *   code?: string
			 * }
			 * ```
			 *
			 * ---
			 *
			 * **Response**
			 * ```ts
			 * type Response = {
			 *   // [title] 状态码
			 *   code: number
			 *   // [title] 提示信息
			 *   message: string
			 *   // [title] 数据
			 *   data?: {
			 *     // [title] 刷新凭证
			 *     refreshToken: string
			 *     // [title] 凭证
			 *     token: string
			 *     // [title] 凭证头
			 *     tokenHead: string
			 *   }
			 * }
			 * ```
			 */
			post_login_auth_login<
				Config extends Alova2MethodConfig<{
					/**
					 * 状态码
					 * ---
					 */
					code: number;
					/**
					 * 提示信息
					 * ---
					 */
					message: string;
					/**
					 * 数据
					 * ---
					 */
					data?: {
						/**
						 * 刷新凭证
						 * ---
						 */
						refreshToken: string;
						/**
						 * 凭证
						 * ---
						 */
						token: string;
						/**
						 * 凭证头
						 * ---
						 */
						tokenHead: string;
					};
				}> & {
					data: {
						username: string;
						password: string;
						code?: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					/**
					 * 状态码
					 * ---
					 */
					code: number;
					/**
					 * 提示信息
					 * ---
					 */
					message: string;
					/**
					 * 数据
					 * ---
					 */
					data?: {
						/**
						 * 刷新凭证
						 * ---
						 */
						refreshToken: string;
						/**
						 * 凭证
						 * ---
						 */
						token: string;
						/**
						 * 凭证头
						 * ---
						 */
						tokenHead: string;
					};
				},
				"login.post_login_auth_login",
				Config
			>;
		};
		schedule: {
			post_schedule_appointment<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: string;
				}> & {
					data: {
						scheduleId: number;
						studentId: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: string;
				},
				"schedule.post_schedule_appointment",
				Config
			>;
			get_schedule_query<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: Array<{
						id?: number;
						startTime?: string;
						endTime?: string;
						courseStatusText?: string;
						scheduleType?: number;
						className?: string;
						courseName?: string;
						teacherName?: string;
						classroomName?: string;
						signInStatusText?: string;
						canSignIn?: boolean;
						canLeave?: boolean;
						canReserve?: boolean;
					}>;
				}> & {
					params?: {
						queryDate?: string;
					};
				},
			>(
				config?: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: Array<{
						id?: number;
						startTime?: string;
						endTime?: string;
						courseStatusText?: string;
						scheduleType?: number;
						className?: string;
						courseName?: string;
						teacherName?: string;
						classroomName?: string;
						signInStatusText?: string;
						canSignIn?: boolean;
						canLeave?: boolean;
						canReserve?: boolean;
					}>;
				},
				"schedule.get_schedule_query",
				Config
			>;
			post_schedule_leave<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: string;
				}> & {
					data: {
						scheduleId: number;
						studentId: number;
						reason: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: string;
				},
				"schedule.post_schedule_leave",
				Config
			>;
			post_schedule_sign_in<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: string;
				}> & {
					data: {
						scheduleId: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: string;
				},
				"schedule.post_schedule_sign_in",
				Config
			>;
		};
		sCenter: {
			get_app_sCenter_advertisement<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						addTime?: string;
						editTime?: string;
						creator?: number;
						editor?: number;
						deleted?: number;
						id?: number;
						title?: string;
						cover?: string;
						content?: string;
						type?: number;
						state?: number;
						sortNum?: number;
					};
				}>,
			>(
				config?: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						addTime?: string;
						editTime?: string;
						creator?: number;
						editor?: number;
						deleted?: number;
						id?: number;
						title?: string;
						cover?: string;
						content?: string;
						type?: number;
						state?: number;
						sortNum?: number;
					};
				},
				"sCenter.get_app_sCenter_advertisement",
				Config
			>;
			get_app_sCenter_advertisementList<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							addTime?: string;
							editTime?: string;
							creator?: number;
							editor?: number;
							deleted?: number;
							id?: number;
							title?: string;
							cover?: string;
							content?: string;
							type?: number;
							state?: number;
							sortNum?: number;
						}>;
					};
				}> & {
					params: {
						pageIndex: number;
						pageSize: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							addTime?: string;
							editTime?: string;
							creator?: number;
							editor?: number;
							deleted?: number;
							id?: number;
							title?: string;
							cover?: string;
							content?: string;
							type?: number;
							state?: number;
							sortNum?: number;
						}>;
					};
				},
				"sCenter.get_app_sCenter_advertisementList",
				Config
			>;
			get_app_sCenter_student_redpoint<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						grade_count?: number;
						evaluate_count?: number;
						homework_count?: number;
					};
				}>,
			>(
				config?: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						grade_count?: number;
						evaluate_count?: number;
						homework_count?: number;
					};
				},
				"sCenter.get_app_sCenter_student_redpoint",
				Config
			>;
		};
		home: {
			get_home_attendance_records_page_query_by_student_id<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id: number;
							signState?: string;
							decLessonCount?: number;
							signType?: string;
							signTime?: string;
							lessonId: number;
							lessonTitle?: string;
							courseName?: string;
							canEvaluate?: boolean;
							date?: string;
							startTime?: string;
							endTime?: string;
						}>;
					};
				}> & {
					params: {
						student_id: number;
						pageIndex: number;
						pageSize: number;
						course_id?: number;
						date?: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id: number;
							signState?: string;
							decLessonCount?: number;
							signType?: string;
							signTime?: string;
							lessonId: number;
							lessonTitle?: string;
							courseName?: string;
							canEvaluate?: boolean;
							date?: string;
							startTime?: string;
							endTime?: string;
						}>;
					};
				},
				"home.get_home_attendance_records_page_query_by_student_id",
				Config
			>;
			post_home_attendance_records_evaluate<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						id?: number;
						date?: string;
						startTime?: string;
						endTime?: string;
						title?: string;
						teacherNames?: string;
						teacherIds?: string;
						assistantNames?: string;
						assistantIds?: string;
						courseName?: string;
						classId?: number;
						roomId?: number;
						className?: string;
						lessonType?: string;
						classroom?: string;
						teachType?: string;
						decCount?: number;
						studentSignState?: string;
						studentDecLessonCount?: number;
						studentSignNum?: number;
						studentNum?: number;
						remark?: string;
						bookable?: boolean;
						state?: string;
						studentCanLeave?: boolean;
						studentCanSign?: boolean;
						teacherCanEvaluate?: boolean;
						signCounts_countTotal?: number;
					};
				}> & {
					params: {
						student_id: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						id?: number;
						date?: string;
						startTime?: string;
						endTime?: string;
						title?: string;
						teacherNames?: string;
						teacherIds?: string;
						assistantNames?: string;
						assistantIds?: string;
						courseName?: string;
						classId?: number;
						roomId?: number;
						className?: string;
						lessonType?: string;
						classroom?: string;
						teachType?: string;
						decCount?: number;
						studentSignState?: string;
						studentDecLessonCount?: number;
						studentSignNum?: number;
						studentNum?: number;
						remark?: string;
						bookable?: boolean;
						state?: string;
						studentCanLeave?: boolean;
						studentCanSign?: boolean;
						teacherCanEvaluate?: boolean;
						signCounts_countTotal?: number;
					};
				},
				"home.post_home_attendance_records_evaluate",
				Config
			>;
			get_home_class_info_query_by_class_id<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						id: number;
						class_name: string;
						teacher_id?: number;
						teacher_name?: string;
						course_id: number;
						course_name: string;
						start_date?: string;
						end_date?: string;
						student_count?: number;
						classroom_id?: number;
						classroom_name?: string;
						remark?: string;
					};
				}> & {
					params?: {
						class_id?: number;
					};
				},
			>(
				config?: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						id: number;
						class_name: string;
						teacher_id?: number;
						teacher_name?: string;
						course_id: number;
						course_name: string;
						start_date?: string;
						end_date?: string;
						student_count?: number;
						classroom_id?: number;
						classroom_name?: string;
						remark?: string;
					};
				},
				"home.get_home_class_info_query_by_class_id",
				Config
			>;
			get_home_class_page_query_by_student_id<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							name?: string;
							course?: string;
							teacher?: string;
							room?: string;
							grade?: string;
							createTime?: string;
							updateTime?: string;
							number?: number;
							courseCount?: number;
							description?: string;
						}>;
					};
				}> & {
					params: {
						course_id: number;
						pageIndex: number;
						pageSize: number;
						teacher_id?: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							name?: string;
							course?: string;
							teacher?: string;
							room?: string;
							grade?: string;
							createTime?: string;
							updateTime?: string;
							number?: number;
							courseCount?: number;
							description?: string;
						}>;
					};
				},
				"home.get_home_class_page_query_by_student_id",
				Config
			>;
			get_home_class_student_list_query_by_class_id<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						student_list?: Array<{
							id?: number;
							name?: string;
							gender?: string;
						}>;
					};
				}> & {
					params?: {
						class_id?: number;
					};
				},
			>(
				config?: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						student_list?: Array<{
							id?: number;
							name?: string;
							gender?: string;
						}>;
					};
				},
				"home.get_home_class_student_list_query_by_class_id",
				Config
			>;
			get_c1_home_card_list<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: Array<{
						id?: number;
						courseId?: number;
						courseName?: string;
						title?: string;
						quantity?: number;
						remainingQuantity?: number;
						lessonCount?: number;
						expireDays?: number;
						endDate?: string;
						state?: number;
						creator?: number;
						editor?: number;
					}>;
				}>,
			>(
				config?: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: Array<{
						id?: number;
						courseId?: number;
						courseName?: string;
						title?: string;
						quantity?: number;
						remainingQuantity?: number;
						lessonCount?: number;
						expireDays?: number;
						endDate?: string;
						state?: number;
						creator?: number;
						editor?: number;
					}>;
				},
				"home.get_c1_home_card_list",
				Config
			>;
			get_c1_home_card_rule<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						content?: string;
						description?: string;
					};
				}>,
			>(
				config?: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						content?: string;
						description?: string;
					};
				},
				"home.get_c1_home_card_rule",
				Config
			>;
			put_c1_card_put<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: string;
				}> & {
					data: {
						userName: string;
						cardName: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: string;
				},
				"home.put_c1_card_put",
				Config
			>;
			get_c1_exchange_query_allGoods<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							deleted?: number;
							id?: number;
							schoolId?: number;
							addTime?: string;
							editTime?: string;
							creator?: number;
							editor?: number;
							materialId?: number;
							categoryId?: number;
							categoryName?: string;
							name?: string;
							credit?: number;
							saleNum?: number;
							viewNum?: number;
							cover?: string;
							content?: string;
							state?: number;
							orgId?: number;
							schoolName?: string;
							storage?: number;
						}>;
					};
				}> & {
					params: {
						pageIndex: number;
						pageSize: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							deleted?: number;
							id?: number;
							schoolId?: number;
							addTime?: string;
							editTime?: string;
							creator?: number;
							editor?: number;
							materialId?: number;
							categoryId?: number;
							categoryName?: string;
							name?: string;
							credit?: number;
							saleNum?: number;
							viewNum?: number;
							cover?: string;
							content?: string;
							state?: number;
							orgId?: number;
							schoolName?: string;
							storage?: number;
						}>;
					};
				},
				"home.get_c1_exchange_query_allGoods",
				Config
			>;
			get_c1_exchange_goods_detail_id<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						deleted?: number;
						id?: number;
						schoolId?: number;
						addTime?: string;
						editTime?: string;
						creator?: number;
						editor?: number;
						materialId?: number;
						categoryId?: number;
						categoryName?: string;
						name?: string;
						credit?: number;
						saleNum?: number;
						viewNum?: number;
						cover?: string;
						content?: string;
						state?: number;
						orgId?: number;
						schoolName?: string;
						storage?: number;
						detailImages?: string;
						specs?: string;
						deliveryInfo?: string;
						limitNum?: number;
						exchangeStartTime?: number;
						exchangeEndTime?: number;
					};
				}> & {
					pathParams: {
						id: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						deleted?: number;
						id?: number;
						schoolId?: number;
						addTime?: string;
						editTime?: string;
						creator?: number;
						editor?: number;
						materialId?: number;
						categoryId?: number;
						categoryName?: string;
						name?: string;
						credit?: number;
						saleNum?: number;
						viewNum?: number;
						cover?: string;
						content?: string;
						state?: number;
						orgId?: number;
						schoolName?: string;
						storage?: number;
						detailImages?: string;
						specs?: string;
						deliveryInfo?: string;
						limitNum?: number;
						exchangeStartTime?: number;
						exchangeEndTime?: number;
					};
				},
				"home.get_c1_exchange_goods_detail_id",
				Config
			>;
			get_c1_exchange_query_acceptGoods<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							addTime?: string;
							editTime?: string;
							creator?: number;
							editor?: number;
							deleted?: number;
							id?: number;
							creditMallId?: number;
							studentId?: number;
							schoolId?: number;
							userId?: number;
							num?: number;
							credit?: string;
							verifyState?: number;
							verifyStaff?: number;
							verifyTime?: string;
							verifyRemark?: string;
							creditMallName?: string;
							cover?: string;
							studentName?: string;
							schoolName?: string;
							mobile?: string;
							verifyStaffName?: string;
						}>;
					};
				}> & {
					params: {
						studentId: number;
						pageIndex: number;
						pageSize: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							addTime?: string;
							editTime?: string;
							creator?: number;
							editor?: number;
							deleted?: number;
							id?: number;
							creditMallId?: number;
							studentId?: number;
							schoolId?: number;
							userId?: number;
							num?: number;
							credit?: string;
							verifyState?: number;
							verifyStaff?: number;
							verifyTime?: string;
							verifyRemark?: string;
							creditMallName?: string;
							cover?: string;
							studentName?: string;
							schoolName?: string;
							mobile?: string;
							verifyStaffName?: string;
						}>;
					};
				},
				"home.get_c1_exchange_query_acceptGoods",
				Config
			>;
			get_c1_exchange_query_rule<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						id?: number;
						settingId?: number;
						name?: string;
						code?: string;
						value?: string;
						valueType?: string;
						info?: string;
						sortNum?: number;
					};
				}> & {
					params: {
						id: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						id?: number;
						settingId?: number;
						name?: string;
						code?: string;
						value?: string;
						valueType?: string;
						info?: string;
						sortNum?: number;
					};
				},
				"home.get_c1_exchange_query_rule",
				Config
			>;
			post_c1_exchange_submit<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						exchangeId?: number;
						orderNo?: string;
						totalCredit?: number;
						status?: number;
						message?: string;
					};
				}> & {
					data: {
						goodsId?: number;
						num?: number;
						receiverName?: string;
						receiverPhone?: string;
						receiverAddress?: string;
						remark?: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						exchangeId?: number;
						orderNo?: string;
						totalCredit?: number;
						status?: number;
						message?: string;
					};
				},
				"home.post_c1_exchange_submit",
				Config
			>;
			get_c1_registration_records_query_records<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							student_id?: number;
							student_name?: string;
							course_id?: number;
							course_name?: string;
							subject_name?: string;
							add_time?: string;
							expire_date?: string;
							amount?: number;
							paid_amount?: number;
							count_lesson_total?: number;
							count_lesson_remaining?: number;
							type?: string;
							verify_state?: string;
							expired?: boolean;
						}>;
					};
				}> & {
					params: {
						student_id: number;
						pageIndex: number;
						pageSize: number;
						exclude_expired?: boolean;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							student_id?: number;
							student_name?: string;
							course_id?: number;
							course_name?: string;
							subject_name?: string;
							add_time?: string;
							expire_date?: string;
							amount?: number;
							paid_amount?: number;
							count_lesson_total?: number;
							count_lesson_remaining?: number;
							type?: string;
							verify_state?: string;
							expired?: boolean;
						}>;
					};
				},
				"home.get_c1_registration_records_query_records",
				Config
			>;
			get_c1_review_records_query_reviews<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							creator_name?: string;
							content?: string;
							score?: number;
							add_time?: string;
						}>;
					};
				}> & {
					params: {
						student_id: number;
						pageIndex: number;
						pageSize: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							creator_name?: string;
							content?: string;
							score?: number;
							add_time?: string;
						}>;
					};
				},
				"home.get_c1_review_records_query_reviews",
				Config
			>;
			get_c1_home_score_query_score_list<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							grade_id?: number;
							grade_title?: string;
							student_id?: number;
							student_name?: string;
							score?: number;
							add_time?: string;
						}>;
					};
				}> & {
					params: {
						student_id: number;
						pageIndex: number;
						pageSize: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							grade_id?: number;
							grade_title?: string;
							student_id?: number;
							student_name?: string;
							score?: number;
							add_time?: string;
						}>;
					};
				},
				"home.get_c1_home_score_query_score_list",
				Config
			>;
			get_c1_homework<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							title?: string;
							courseName?: string;
							teacherName?: string;
						}>;
					};
				}> & {
					params: {
						pageIndex: number;
						pageSize: number;
						title?: string;
						courseName?: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						pageIndex: number;
						pageSize: number;
						total: number;
						pages: number;
						rows?: Array<{
							id?: number;
							title?: string;
							courseName?: string;
							teacherName?: string;
						}>;
					};
				},
				"home.get_c1_homework",
				Config
			>;
			get_c1_homework_detail<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data?: {
						homework_id?: string;
						title?: string;
						class_name?: string;
						content?: string;
					};
				}> & {
					params: {
						id: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data?: {
						homework_id?: string;
						title?: string;
						class_name?: string;
						content?: string;
					};
				},
				"home.get_c1_homework_detail",
				Config
			>;
			post_c1_homework_submit<
				Config extends Alova2MethodConfig<{
					recordId?: number;
					homeworkId?: number;
					studentId?: number;
					content?: string;
					images?: string;
					addTime?: string;
				}> & {
					params: {
						studentId: number;
					};
					data?: {
						homeworkId?: number;
						content?: string;
						images?: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					recordId?: number;
					homeworkId?: number;
					studentId?: number;
					content?: string;
					images?: string;
					addTime?: string;
				},
				"home.post_c1_homework_submit",
				Config
			>;
			delete_c1_homework_delete<
				Config extends Alova2MethodConfig<{
					recordId?: number;
					homeworkId?: number;
					studentId?: number;
					content?: string;
					images?: string;
					addTime?: string;
				}> & {
					params: {
						homeworkId: number;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					recordId?: number;
					homeworkId?: number;
					studentId?: number;
					content?: string;
					images?: string;
					addTime?: string;
				},
				"home.delete_c1_homework_delete",
				Config
			>;
		};
		article: {
			/**
			 * ---
			 *
			 * [GET] 获取文章列表
			 *
			 * **path:** /article
			 *
			 * ---
			 *
			 * **Query Parameters**
			 * ```ts
			 * type QueryParameters = {
			 *   // 页码
			 *   pageIndex?: number
			 *   // 每页数据条数
			 *   pageSize?: number
			 *   // 标题
			 *   title?: string
			 * }
			 * ```
			 *
			 * ---
			 *
			 * **Response**
			 * ```ts
			 * type Response = {
			 *   // 状态码
			 *   code: number
			 *   // 提示信息
			 *   message: string
			 *   // 数据
			 *   data: {
			 *     // 页码
			 *     pageIndex: number
			 *     // 每页数据条数
			 *     pageSize: number
			 *     // 数据总数
			 *     total: number
			 *     // 总页数
			 *     pages: number
			 *     // 当前页数据
			 *     // [items] start
			 *     // [items] end
			 *     rows: Array<{
			 *       // 唯一标识
			 *       id: string
			 *       // 标题
			 *       title: string
			 *       // 关键词
			 *       keywords: string
			 *       // 摘要
			 *       summary: string
			 *       // 内容
			 *       content: string
			 *       // 发布日期
			 *       date: string
			 *     }>
			 *   }
			 * }
			 * ```
			 */
			get_article<
				Config extends Alova2MethodConfig<{
					/**
					 * 状态码
					 */
					code: number;
					/**
					 * 提示信息
					 */
					message: string;
					/**
					 * 数据
					 */
					data: {
						/**
						 * 页码
						 */
						pageIndex: number;
						/**
						 * 每页数据条数
						 */
						pageSize: number;
						/**
						 * 数据总数
						 */
						total: number;
						/**
						 * 总页数
						 */
						pages: number;
						/**
						 * 当前页数据
						 */
						rows: Array<{
							/**
							 * 唯一标识
							 */
							id: string;
							/**
							 * 标题
							 */
							title: string;
							/**
							 * 关键词
							 */
							keywords: string;
							/**
							 * 摘要
							 */
							summary: string;
							/**
							 * 内容
							 */
							content: string;
							/**
							 * 发布日期
							 */
							date: string;
						}>;
					};
				}> & {
					params: {
						/**
						 * 页码
						 */
						pageIndex?: number;
						/**
						 * 每页数据条数
						 */
						pageSize?: number;
						/**
						 * 标题
						 */
						title?: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					/**
					 * 状态码
					 */
					code: number;
					/**
					 * 提示信息
					 */
					message: string;
					/**
					 * 数据
					 */
					data: {
						/**
						 * 页码
						 */
						pageIndex: number;
						/**
						 * 每页数据条数
						 */
						pageSize: number;
						/**
						 * 数据总数
						 */
						total: number;
						/**
						 * 总页数
						 */
						pages: number;
						/**
						 * 当前页数据
						 */
						rows: Array<{
							/**
							 * 唯一标识
							 */
							id: string;
							/**
							 * 标题
							 */
							title: string;
							/**
							 * 关键词
							 */
							keywords: string;
							/**
							 * 摘要
							 */
							summary: string;
							/**
							 * 内容
							 */
							content: string;
							/**
							 * 发布日期
							 */
							date: string;
						}>;
					};
				},
				"article.get_article",
				Config
			>;
			/**
			 * ---
			 *
			 * [POST] 新增文章
			 *
			 * **path:** /article
			 *
			 * ---
			 *
			 * **RequestBody**
			 * ```ts
			 * type RequestBody = {
			 *   // 标题
			 *   title: string
			 *   // 关键字
			 *   keywords: string
			 *   // 摘要
			 *   summary: string
			 *   // 内容
			 *   content: string
			 * }
			 * ```
			 *
			 * ---
			 *
			 * **Response**
			 * ```ts
			 * type Response = {
			 *   code: number
			 *   message: string
			 *   data: string
			 * }
			 * ```
			 */
			post_article<
				Config extends Alova2MethodConfig<{
					code: number;
					message: string;
					data: string;
				}> & {
					data: {
						/**
						 * 标题
						 */
						title: string;
						/**
						 * 关键字
						 */
						keywords: string;
						/**
						 * 摘要
						 */
						summary: string;
						/**
						 * 内容
						 */
						content: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					code: number;
					message: string;
					data: string;
				},
				"article.post_article",
				Config
			>;
			/**
			 * ---
			 *
			 * [PUT] 修改文章
			 *
			 * **path:** /article
			 *
			 * ---
			 *
			 * **RequestBody**
			 * ```ts
			 * type RequestBody = {
			 *   // 唯一标识
			 *   id: string
			 *   // 标题
			 *   title: string
			 *   // 关键字
			 *   keywords?: string
			 *   // 摘要
			 *   summary?: string
			 *   // 内容
			 *   content?: string
			 * }
			 * ```
			 *
			 * ---
			 *
			 * **Response**
			 * ```ts
			 * type Response = {
			 *   // 状态码
			 *   code: number
			 *   // 提示信息
			 *   message: string
			 *   // 唯一标识
			 *   data: string
			 * }
			 * ```
			 */
			put_article<
				Config extends Alova2MethodConfig<{
					/**
					 * 状态码
					 */
					code: number;
					/**
					 * 提示信息
					 */
					message: string;
					/**
					 * 唯一标识
					 */
					data: string;
				}> & {
					data: {
						/**
						 * 唯一标识
						 */
						id: string;
						/**
						 * 标题
						 */
						title: string;
						/**
						 * 关键字
						 */
						keywords?: string;
						/**
						 * 摘要
						 */
						summary?: string;
						/**
						 * 内容
						 */
						content?: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					/**
					 * 状态码
					 */
					code: number;
					/**
					 * 提示信息
					 */
					message: string;
					/**
					 * 唯一标识
					 */
					data: string;
				},
				"article.put_article",
				Config
			>;
			/**
			 * ---
			 *
			 * [DELETE] 删除文章
			 *
			 * **path:** /article/{id}
			 *
			 * ---
			 *
			 * **Path Parameters**
			 * ```ts
			 * type PathParameters = {
			 *   // 唯一标识
			 *   id: string
			 * }
			 * ```
			 *
			 * ---
			 *
			 * **Response**
			 * ```ts
			 * type Response = {
			 *   // 状态码
			 *   code: number
			 *   // 提示信息
			 *   message: string
			 *   // 唯一标识
			 *   data: string
			 * }
			 * ```
			 */
			delete_article_id<
				Config extends Alova2MethodConfig<{
					/**
					 * 状态码
					 */
					code: number;
					/**
					 * 提示信息
					 */
					message: string;
					/**
					 * 唯一标识
					 */
					data: string;
				}> & {
					pathParams: {
						/**
						 * 唯一标识
						 */
						id: string;
					};
				},
			>(
				config: Config,
			): Alova2Method<
				{
					/**
					 * 状态码
					 */
					code: number;
					/**
					 * 提示信息
					 */
					message: string;
					/**
					 * 唯一标识
					 */
					data: string;
				},
				"article.delete_article_id",
				Config
			>;
		};
	}

	var Apis: Apis;
}
