spring:
  datasource:
    username: root
    password: 123456
    druid:
     max-active: 5
  redis:
    host: 192.168.220.128
    port: 6379
    password: 01star
  data:
    mongodb:
    password: 123456
    druid:
     max-active: 5
  redis:
    host: 192.168.220.128
    port: 6379
    password: 01star
  data:
    mongodb:
      uri: mongodb://awei:123456@192.168.220.128:27017/firstDb
    port: 6379
    password: 01star
  data:
    mongodb:
      uri: mongodb://awei:123456@192.168.220.128:27017/firstDb      uri: mongodb://htl:123456@192.168.80.128:27017/firstDb