/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/home/index" |
  "/pages/mine/index" |
  "/pages/schedule/index" |
  "/pages/select/index" |
  "/subPages/login/forget" |
  "/subPages/login/register" |
  "/subPages/mine/about" |
  "/subPages/mine/them" |
  "/subPages/parent/attendance-record" |
  "/subPages/parent/class-page" |
  "/subPages/parent/comment-record" |
  "/subPages/parent/goods-detail" |
  "/subPages/parent/homework-detail" |
  "/subPages/parent/homework-list" |
  "/subPages/parent/notice-list" |
  "/subPages/parent/points-mall" |
  "/subPages/parent/points-record" |
  "/subPages/parent/score-list" |
  "/subPages/parent/signup-record" |
  "/subPages/parent/student-list" |
  "/subPages/parent/trial-card";

interface NavigateToOptions {
	url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
	url: "/pages/home/index" | "/pages/schedule/index" | "/pages/select/index" | "/pages/mine/index";
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
	navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
	redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
	switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
	reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
	export type LocationUrl = _LocationUrl;
}
