#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 31 20:15:26 CST 2026
maven-metadata-snapshots.xml.error=
maven-metadata-2383166-snapshot-6TSW5l.xml.lastUpdated=1774959326112
maven-metadata-aliyun.xml.error=
maven-metadata-snapshots.xml.lastUpdated=1774959326111
maven-metadata-aliyun.xml.lastUpdated=1774959326113
