#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 31 20:15:30 CST 2026
maven-metadata-snapshots.xml.error=
maven-metadata-2383166-snapshot-6TSW5l.xml.lastUpdated=1774959330946
maven-metadata-aliyun.xml.error=
maven-metadata-snapshots.xml.lastUpdated=1774959330945
maven-metadata-aliyun.xml.lastUpdated=1774959330946
