#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Apr 02 18:30:35 CST 2026
maven-metadata-mirror.xml.lastUpdated=1775125835695
maven-metadata-2383166-snapshot-6TSW5l.xml.lastUpdated=1775125835696
maven-metadata-2383166-snapshot-6TSW5l.xml.error=
maven-metadata-snapshots.xml.lastUpdated=1775125835696
maven-metadata-aliyun.xml.lastUpdated=1775125835696
