#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 31 20:15:31 CST 2026
maven-metadata-mirror.xml.lastUpdated=1774959331872
maven-metadata-2383166-snapshot-6TSW5l.xml.lastUpdated=1774959331873
maven-metadata-2383166-snapshot-6TSW5l.xml.error=
maven-metadata-snapshots.xml.lastUpdated=1774959331873
maven-metadata-aliyun.xml.lastUpdated=1774959331873
