#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Apr 02 18:30:36 CST 2026
maven-metadata-snapshots.xml.error=
maven-metadata-2383166-snapshot-6TSW5l.xml.lastUpdated=1775125836054
maven-metadata-aliyun.xml.error=
maven-metadata-snapshots.xml.lastUpdated=1775125836054
maven-metadata-aliyun.xml.lastUpdated=1775125836055
